services:
  app:
    image: hagemi:latest
    build:  
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7860:7860"
    env_file:
      - .env
    
networks:
  default: 
